Update script for MacOS M1
agendrix/laptop pull request #4
Opened 2021-10-18 20:44 UTC by stivaugoin

Reference for homebrew modification: https://mac.install.guide/homebrew/index.html

Reference for Postgresql & Ruby modification: @LouisBoudreau 💪

2021-10-18 20:47 UTC, ericmatte commented on mac
> +    append_to_zshrc 'eval "$(/opt/homebrew/bin/brew shellenv)"'
Je ne suis pas certain que cela fonctionne sur les ordis non-m1 🤔 

![image](https://user-images.githubusercontent.com/9013072/137804333-04be16d3-7d48-43a5-b729-eacd5fcc98ff.png)

(À moins qu'il me manquerait quelque chose)

2021-10-18 20:48 UTC, ericmatte commented on mac
> +    eval "$(/opt/homebrew/bin/brew shellenv)"
Pourquoi la commande est en double?

2021-10-18 20:49 UTC, ericmatte commented on mac
> +  rbenv install -s "$ruby_version"
On a plus besoin de cela?

2021-10-18 20:49 UTC, ericmatte commented on mac
> +    append_to_zshrc 'eval "$(/opt/homebrew/bin/brew shellenv)"'
Je vois que plus tard dans le script tu fais un `ln -sf` vers `/opt/homebrew/var/postgres`; est-ce que ça se peut que l'on en aille besoin plus tôt?

2021-10-19 11:52 UTC, stivaugoin commented on mac
> +    append_to_zshrc 'eval "$(/opt/homebrew/bin/brew shellenv)"'
Est-ce que ce script est utilisé souvent sur un "vieux" laptop? Si on assume que ce script sert seulement à configurer un nouveau laptop j'imagine qu'on peut aussi assumer qu'il sera seulement utilisé sur des M1.
Dans le cas contraire, j'aime bien l'idée de Louis de définir une variable selon `arch`. 

Pour le `ln -sf`, j'ai ajouté le `f` parce que si je roule le script une 2e fois, le `ln` existe déjà. Mais, je n'ai pas vraiment d'expérience avec ce genre de commande malheureusement. Il y a peut-être une meilleur stratégie.

2021-12-16 03:12 UTC, ericmatte requested changes

2021-12-16 03:12 UTC, ericmatte commented on mac
>    fancy_echo "Symlink postgresql@13 binary to /usr/local/bin..."
@stivaugoin pour moi sur mon nouveau M1, le script de la PR n'a pas fonctionné:

![image](https://user-images.githubusercontent.com/9013072/146301429-24f192a7-317a-440e-963d-f6297a51da2a.png)

Par contre, ça l'a passé avec le script sur master.

2021-12-16 13:11 UTC, stivaugoin commented on mac
>    fancy_echo "Symlink postgresql@13 binary to /usr/local/bin..."
🤔 ça c'est bizarre!

Il y a peut-être une différence avec Monterey? Quand je l'ai roulé je n'était pas encore sur Monterey. J'imagine que toi tu es déjà dessus?! 🤔

2021-12-16 20:48 UTC, ericmatte commented on mac
>    fancy_echo "Symlink postgresql@13 binary to /usr/local/bin..."
Oui je suis sur Monterey! Mais je ne suis pas certain de ce que ça change 🤔

2021-12-20 19:08 UTC, LouisBoudreau commented
@ericmatte finalement le support pour les mac m1 a été ajouté dans cette [PR](https://github.com/agendrix/laptop/pull/5). Je vais donc fermer celle-ci

2021-12-20 19:08 UTC, closed without merging